version: '2'
services:
  ckan:
    image: nhong/ckan
    ports:
     - "8080"
    depends_on:
     - postgres
     - solr
    links:
     - postgres:ckan-postgres
     - solr:ckan-solr
  postgres:
    image: postgres
    ports:
     - "5432"
    volumes:
     - /var/lib/postgresql/data
  solr:
    image: nhong/solr-tomcat
    ports:
     - "8983"
