version: '2'
services:
  ckan:
    build:
      context: .
      args:
        POSTGRES_USER: postgres
        POSTGRES_PASS: mysecretpassword
        POSTGRES_HOST: postgres
        POSTGRES_DB: postgres
        SOLR_HOST: solr
        SOLR_USER: solr
    ports:
     - "80:80"
     - "443:443"
    depends_on:
     - postgres
     - solr
  postgres:
    image: postgres
    ports:
     - "5432:5432"
    volumes:
     - /opt/ckan/data:/var/lib/postgresql/data
  solr:
    image: nhong/solr-tomcat
    ports:
     - "8983:8983"
